### ISSUE TITLE
Local work ok,Server not work

### ISSUE THREAD

**Issue by imnpc** [badinansoft/nova-language-switch#12]
Hello,

I test this on the local is work ok,  use lang: en And zh_CN,
But on the server,can not work,cache key is ok.

CACHE_DRIVER=redis

**Comment by imnpc** [comment]
1.Middleware/LanguageSwitch
2.app()->setLocale(strtolower($lang));    
zh_CN => zh_cn ？
3.now load: resources/lang/vendor/nova/zh_cn.json
but need load :resources/lang/vendor/nova/zh_CN.json

**Comment by shahabzebare** [comment]
fixed at last version try update it will work

**Comment by imnpc** [comment]
use zh_CN not work
use zh_cn work
