### ISSUE TITLE
Wrapping issue

### ISSUE THREAD

**Issue by guybrun** [badinansoft/nova-language-switch#17]
There seems to be a small wrapping issue with the menu bar icon when upgrading from Nova 4.29.0 ang higher. See attached img.
![img_wrapping_issue](https://github.com/badinansoft/nova-language-switch/assets/11294565/c9ebaf49-d2da-42d0-8260-a08169fa07ff)

Regards,
Guy

**Comment by philipbaginski** [comment]
The same. Trying to find reason, but I could not find it.

**Comment by philipbaginski** [comment]
It needs just tiny adjustment : added  flex items-center into this div:

<DropdownTrigger :show-arrow="false" class="h-10 w-full hover:text-primary-500 flex items-center">

**Comment by krepysh-spec** [comment]
@badinansoft Hi! When fix this ?

**Comment by adilth** [comment]
i add this in my app.css in public folder and it fix 
`[data-v-app] dropdowntrigger {
  display: flex;
  align-items: center;
  cursor: pointer;
}`

**Comment by pointybeard** [comment]
Just send a PR with changes mentioned above.

**Comment by shahabzebare** [comment]
It will fix in new version thanks [pointybeard](https://github.com/pointybeard) for your contribution
