### ISSUE TITLE
Improvement on mobile device view

### ISSUE THREAD

**Issue by scramatte** [badinansoft/nova-language-switch#5]
Hello,

Does it possible to improve mobile device view ?

![IMG_D656BB3264AD-1](https://user-images.githubusercontent.com/188766/213680252-281d0b02-1f0a-4356-888a-72a3f2d08499.jpeg)

Can you remove language label on small mobile devices?

Regards

**Comment by scramatte** [comment]
I've send to you a PR for this feature. Hope that helps

**Comment by badinansoft** [comment]
Meareged thanks for your contribution
