### ISSUE TITLE
localization for the config file

### ISSUE THREAD

**Issue by DylanovE** [badinansoft/nova-language-switch#6]
is there any possible way to localize the config file, as the languagelist in there doesnt translate along with the language selected.
if i for example am on dutch localization it should say nederlands, but it still remains dutch.

**Comment by DylanovE** [comment]
also i was hoping to see if someone could help me with the setup as something must be setup wrong, when i click on another language it doesnt change anything at all. it just remains what i have set in config/app.php as 'locale', making it empty changes nothing it will just go to the fallback_locale.

my env file has `CACHE_DRIVER=file`|
in app/providers/novaserviceprovider the tools function:
`
    public function tools()
    {
        return [
            new \Badinansoft\LanguageSwitch\LanguageSwitch(),
        ];
    }`
    
    i did publish the config file and fill it with currently translated languages.|
    
    app/http/kernel.php middelwaregroups looks like this:
   `    protected $middlewareGroups = [
        'web' => [
            \Badinansoft\LanguageSwitch\Http\Middleware\LanguageSwitch::class,
        ],
    ];`
    
    so there should be nothing wrong, right?

**Comment by badinansoft** [comment]
I don't understand well can you give me code example

**Comment by killgt** [comment]
I think he  is asking to resolve the supported languages runtime, so you can translate 'spanish' to 'Español'. Maybe the language switcher can read from laravel translations instead of directly displaying the value from the config file.

**Comment by badinansoft** [comment]
Aha yah is nice idea i will check many thank for your contribution Mr @killgt
